### ISSUE TITLE
Question: Can the counter be any value?

### ISSUE THREAD

**Issue by alpominth** [crisdosyago/discohash#9]
There is a counter in DiscoHash: https://github.com/crisdosyago/discohash/blob/master/src/discohash.cpp#L75

Can it be any value?

If it can, it could be used to make a stream cipher out of this hash function.

**Comment by crisdosyago** [comment]
Good question! Thanks for the idea! Let’s investigate this.

looking at the line it seems definitely I designed it to be a nothing up my sleeve value. Theoretically it could take any value.

my concerns / thoughts are (and I’m not immediately sure how relevant these all are):

- I developed the randomness of this function through testing with SMHASHER, so is possible that it’s finely tuned and changing a value could unravel it, but it may not be likely
- SMASHER already identifies some weak seed values, not sure how relevant this is for encryption but it’s something I had wanted to come back to and work on a fix for sometime


anyway this is a nice find. Let’s try to make this happen. What’s your specific idea for how to do, and how do you think we can evaluate it?

**Comment by crisdosyago** [comment]
Thanks @alpominth

**Comment by crisdosyago** [comment]
Sounds like an interesting bit of work you’re about to do! Thank you for sharing! Well best of luck with it @alpominth!

I’ll close this issue now because it’s about discussing an idea and we’ve done that. Thank you. Have a good one! 😀😜

**Comment by crisdosyago** [comment]
> Thank you Man!

You're welcome!

> PS: You could activate the "Discussions" session in this repository, it would help cryptanalists to share their knowledge and helping developing Discohash.


Done! :)
